server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: inventory-management-system

  # Database Configuration
  datasource:
    # H2 Database (for development/testing)
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

    # MySQL Configuration (uncomment for production)
    # url: jdbc:mysql://localhost:3306/inventory_management
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # username: your_username
    # password: your_password

    # PostgreSQL Configuration (uncomment for production)
    # url: jdbc:postgresql://localhost:5432/inventory_management
    # driver-class-name: org.postgresql.Driver
    # username: your_username
    # password: your_password

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop  # Use 'update' for production
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # dialect: org.hibernate.dialect.MySQL8Dialect  # for MySQL
        # dialect: org.hibernate.dialect.PostgreSQLDialect  # for PostgreSQL
        format_sql: true
        use_sql_comments: true

  # H2 Console (for development only)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000  # 24 hours in milliseconds

# CORS Configuration
cors:
  allowed-origins: http://localhost:3000,http://127.0.0.1:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Logging Configuration
logging:
  level:
    com.inventory: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Application specific properties
app:
  admin:
    username: admin
    password: admin123
  timezone: UTC